# Generated by Django 6.0.3 on 2026-03-15 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_year', models.IntegerField(blank=True, null=True)),
                ('height_in', models.FloatField(blank=True, null=True)),
                ('weight_lb', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AthleteTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(auto_now_add=True)),
                ('sprint_40yd', models.FloatField(blank=True, null=True)),
                ('sprint_30m', models.FloatField(blank=True, null=True)),
                ('flying_sprint', models.FloatField(blank=True, null=True)),
                ('accel_10m', models.FloatField(blank=True, null=True)),
                ('split_5m', models.FloatField(blank=True, null=True)),
                ('split_10m', models.FloatField(blank=True, null=True)),
                ('split_20m', models.FloatField(blank=True, null=True)),
                ('agility_t', models.FloatField(blank=True, null=True)),
                ('shuttle_run', models.FloatField(blank=True, null=True)),
                ('lateral_agility', models.FloatField(blank=True, null=True)),
                ('illinois_agility', models.FloatField(blank=True, null=True)),
                ('beep_level', models.FloatField(blank=True, null=True)),
                ('cooper_test', models.FloatField(blank=True, null=True)),
                ('interval_run', models.FloatField(blank=True, null=True)),
                ('vertical_jump', models.FloatField(blank=True, null=True)),
                ('broad_jump', models.FloatField(blank=True, null=True)),
                ('medicine_ball_throw', models.FloatField(blank=True, null=True)),
                ('push_ups', models.FloatField(blank=True, null=True)),
                ('sit_ups', models.FloatField(blank=True, null=True)),
                ('plank', models.FloatField(blank=True, null=True)),
                ('lunges', models.FloatField(blank=True, null=True)),
                ('box_jump', models.FloatField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.athlete')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='DivisionBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('raw_value', models.CharField(max_length=100)),
                ('threshold_min', models.FloatField(blank=True, null=True)),
                ('threshold_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('division', 'test_name')},
            },
        ),
    ]
